services:
  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    restart: always
    environment:
        - NEO4J_AUTH=neo4j/hogehoge123
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'